### ISSUE TITLE
Problem trying to load the amplitude_histogram plugin

### ISSUE THREAD

**Issue by Sergudx** [kwikteam/phy-contrib#153]
Hello.

I am trying to activate the amplitude_histogram plugin but it's giving me the error below. Any ideas of how to fix it?

17:38:25 [E] plugin:109           cannot import name 'AsyncCaller'
Traceback (most recent call last):
  File "c:\users\martinez-bellver.ser\appdata\local\continuum\anaconda3\envs\klusta\lib\site-packages\phy\utils\plugin.py", line 107, in discover_plugins
    mod = imp.load_module(modname, file, path, descr)  # noqa
  File "c:\users\martinez-bellver.ser\appdata\local\continuum\anaconda3\envs\klusta\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "c:\users\martinez-bellver.ser\appdata\local\continuum\anaconda3\envs\klusta\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Martinez-Bellver.Ser\.phy\plugins\amplitude_histogram.py", line 25, in <module>
    from phy.gui.qt import AsyncCaller, busy_cursor
ImportError: cannot import name 'AsyncCaller

Thanks in advance,

Sergio

**Comment by DJ-Hayden** [comment]
Hey Sergudx,

So if you look at the steps outlined in my comment/update [here]( https://github.com/kwikteam/phy/issues/798) you'll get most everything you need. All you need to do after following those steps is to follow the directions within the amplitude_histogram.py [file](https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/views/amplitude_histogram.py).
