### ISSUE TITLE
Problem with amplitude_histogram.py plugin

### ISSUE THREAD

**Issue by PhantomSpike** [kwikteam/phy-contrib#155]
Hi,

Firstly, thank you so much guys for developing Phy and putting all this effort. It works quite nice so far and it has been very useful.

I wanted to use the amplitude_histogram plug in. I followed the instructions and put the amplitude_histogram.py file in the ~/.phy/plugins folder which I created along with copying this line into the phy_config.py file so that it looks like this:

try:
    import phycontrib
except:
    pass

c = get_config()
c.Plugins.dirs = [r'/home/alex/.phy/plugins/']
**c.TemplateGUI.plugins = ['AmplitudeHistogram']**

  I keep getting the following error however:

""phy template-gui params.py 
22:09:56 [E] plugin:109           cannot import name 'AsyncCaller'
Traceback (most recent call last):
  File "/home/alex/.conda/envs/phy/lib/python3.5/site-packages/phy/utils/plugin.py", line 107, in discover_plugins
    mod = imp.load_module(modname, file, path, descr)  # noqa
  File "/home/alex/.conda/envs/phy/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/alex/.conda/envs/phy/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/alex/.phy/plugins/amplitude_histogram.py", line 25, in <module>
    from phy.gui.qt import AsyncCaller, busy_cursor
ImportError: cannot import name 'AsyncCaller' ''

Any ideas why this might be happening?

Best wishes,

Alex

**Comment by PhantomSpike** [comment]
Hi,

I just realized that this is a duplication of this topic:

https://github.com/kwikteam/phy-contrib/issues/153

The solution offered by https://github.com/DJ-Hayden seems to work very well. :)
