### ISSUE TITLE
execution of phy GUI is aborted if I export PCs from Spyking-Circus

### ISSUE THREAD

**Issue by SaraMati** [kwikteam/phy-contrib#160]
I use phy to further sort results of Spyking-Circus on a Windows machine. 
if I choose to export principle components the phy GUI won't open with this error message: 
 ``File format hdf5 is not supported by phy. TraceView disabled'' 
It's not an error message since the line after says "Launching the phy GUI", but it won't open. 

if this helps: when I run the params.py in debug mode this is the error message: 

21:04:49 [E] cli:36               An error has occurred (SyntaxError): (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: malformed \N character escape (<string>, line 7)
21:04:49 [D] cli:39               Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\phy-script.py", line 11, in <module>
    load_entry_point('phy==1.0.9', 'console_scripts', 'phy')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\gui.py", line 599, in gui
    params = _read_python(params_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\phy\utils\_misc.py", line 134, in _read_python
    exec_(contents, {}, metadata)
  File "<string>", line 7
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: malformed \N character escape

will be grateful if you help fix this issue

**Comment by rossant** [comment]
My guess is that you have a line like `dat_path = "C:\path\to\file.dat"` somewhere in your prm file (a string with backslashes). Just add a `r` character just before the opening quote: `dat_path = r"C:\path\to\file.dat"`

This is because backslashes used by Windows for paths have special meaning when used in strings, and they should be escaped.

**Comment by SaraMati** [comment]
can you interpret this error log please?

(base) C:\Users\saram\Desktop\20150127_400_0\data\data.GUI>phy template-gui params.py --debug
11:54:53 [D] model:381            Loading spike clusters.
11:54:53 [D] model:396            Loading templates.
11:54:53 [E] cli:36               An error has occurred (AssertionError):
11:54:53 [D] cli:39               Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\phy-script.py", line 11, in <module>
    load_entry_point('phy==1.0.9', 'console_scripts', 'phy')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\gui.py", line 602, in gui
    _run_cmd('_run(params)', ctx, globals(), locals())
  File "C:\ProgramData\Anaconda3\lib\site-packages\phy\utils\cli.py", line 73, in _run_cmd
    return exec_(cmd, glob, loc)
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\gui.py", line 574, in _run
    controller = TemplateController(**params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\gui.py", line 86, in __init__
    self.model = TemplateModel(dat_path, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\model.py", line 188, in __init__
    self._load_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\model.py", line 237, in _load_data
    self.sparse_templates = self._load_templates()
  File "C:\ProgramData\Anaconda3\lib\site-packages\phycontrib\template\model.py", line 401, in _load_templates
    assert data.ndim == 3
AssertionError

**Comment by yger** [comment]
This is because phy can not handle properly PCs/templates that will only be on a single electrode (see template/model.py L306, the use of the squeeze() function prevents the use of data on a single channel only)

**Comment by SaraMati** [comment]
yes, the problem was solved when deleted the squeeze command

**Comment by rossant** [comment]
to reopen in the phy repository if the problem still exists in the dev branch
